config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: :task_edit
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:show, :destroy, :edit, :update]
  def index
  @tasks = Task.all
  end

  def new
    @task = Task.new # needed to instantiate the form_for
  end

  def create
    @task = Task.new(task_params)
    @task.save

    # no need for app/views/restaurants/create.html.erb
    redirect_to tasks_path(@task)
  end

  def show
  end

  def edit
  
  end

  def update
    @task.update(task_params)
    
    redirect_to tasks_path(@task)
  end

  def destroy
    @task.destroy

    
    redirect_to tasks_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:name, :details)
  end
  private

  def set_task
    @task = Task.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul class="list">
  <% @tasks.each do |task| %>
    <li><%= link_to task.name, task_path(task.id) %></li>
  <% end %>
</ul>
<p><%= link_to "Add new task", tasks_new_path %></p>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<%= link_to  task_edit_path(@task) do %>
  <input type="button" id="edit-button" name="name">
<% end %>

<h1><%= @task.name %></h1>

<div id="b"> <%= @task.details %></div>
<input type="checkbox" id="laundry" name="name">
<label for="check"> This task is not completed yet</label><br>
<p><%= link_to "back to list", tasks_path %></p>

<%= link_to "Delete #{@task.name}",
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>